version: '3.7'
services:
  gitlab-ce:
    image: gitlab/gitlab-ce:16.2.4-ce.0
    restart: always
    hostname: '${DOCKER_GITLAB_IP}'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${DOCKER_GITLAB_IP}'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./gitlab/gitlab/config:/etc/gitlab
      - ./gitlab/gitlab/logs:/var/log/gitlab
      - ./gitlab/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:v16.2.1
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner:/etc/gitlab-runner
    networks:
      - gitlab

volumes:
  gitlab-runner:

networks:
  gitlab:
    name: gitlab-network